[build]
  publish = "dist"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "14"
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';font-src fonts.gstatic.com;style-src 'self' fonts.googleapis.com cdn.jsdelivr.net 'unsafe-inline'"
