version: 2

jobs:
  build_test:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Installing dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Linting Code
          command: npm run lint

  deploy:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Installing dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_test
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build_test
