version: 2

jobs:
  build_test:
    docker:
      - image: cypress/base:8

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Installing dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Linting Code
          command: npm run lint

      - run:
          name: Running unit tests
          command: npm run test:unit

      - run:
          name: Running e2e tests
          command: npm run test:e2e -- --headless

      - store_artifacts:
          path: tests/e2e/screenshots

  deploy:
    docker:
      - image: cypress/base:8

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Installing dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Deploying
          command: sh deploy.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_test
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build_test
