# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/base:8
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}

      - run: 
          name: Installing dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}
        
      - run: 
          name: Linting Code
          command: npm run lint

      - run: 
          name: Running unit tests
          command: npm run test:unit

      - run: 
          name: Running e2e tests
          command: npm run test:e2e:ci

      - store_artifacts:
          path: tests/e2e/screenshots

      - run:
          name: Deploying
          command: sh deploy.sh
